# This is a basic workflow to help you get started with Actions

name: compile jar

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Build engine
        working-directory: litiengine
        run: |
          sudo chmod 777 -R .
          ./gradlew clean distZip publishToMavenLocal -x test

      - name: Build example
        run: |
          mvn clean install

      - name: Commit jar to build branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp target/jam.jar jam.jar
          git add -f jam.jar
          git commit -m "Update GameJam-Jar by workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "build"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
